version = "3.7.12"
style = defaultWithAlign # For pretty alignment.
maxColumn = 90
continuationIndent.defnSite = 6
align.arrowEnumeratorGenerator = true
binPack.parentConstructors = true
align.openParenCallSite = false
rewrite.rules = [SortImports, PreferCurlyFors]
danglingParentheses.preset = true
runner.dialect = scala3
