rules = [
  OrganizeImports,
  NoAutoTupling,
  DisableSyntax,
  LeakingImplicitClassVal,
  NoValInForComprehension,
  ProcedureSyntax
]

OrganizeImports {
  removeUnused = true
  targetDialect = Scala3
  groupedImports = Merge
}
